### ISSUE TITLE
Is it possible to expand the relevant example

### ISSUE THREAD

**Issue by mdxiaohu** [georapbox/mutation-observer-element#1]
MutationObserverElement.defineCustomElement()

Do I want to pass in the dom element that needs to be monitored.

**Comment by georapbox** [comment]
Hi,

I'm not really sure I understand your question, but I'll give it a try nevertheless.

`MutationObserverElement.defineCustomElement()` is a static method to lazily define the custom element (web component), not the element that is to be monitored.

If you don't want to lazily define the custom element you can always use the alternative import method as documented [here](https://github.com/georapbox/mutation-observer-element#script), which automatically defines the custom element.

The element to be monitored needs to be wrapped by the custom element. For example:

```html
<mutation-observer>
  <div id="element-to-monitor"></div>
</mutation-observer>
```

In the above example, the `div` with id `element-to-monitor` is the element to be monitored for mutations.

Is this answering you question?

**Comment by mdxiaohu** [comment]
@georapbox
Yes, I have used it in vue2.
I'm not very familiar with this api, still trying.
thank you for your reply.

**Comment by georapbox** [comment]
I think that you will be OK if you just import the module using the alternative method that automatically defines the element. You can find more info about defining custom elements [here](https://web.dev/custom-elements-v1/#defining-a-new-element). This is actually what [`MutationObserverElement.defineCustomElement()`](https://github.com/georapbox/mutation-observer-element/blob/main/src/mutation-observer.js#L181) is doing under the hood.

Also in the [demo](https://georapbox.github.io/mutation-observer-element/) page you can find a few usage examples with the source code that might come handy.
